import {MainEvent} from './MainEvent';
import {SharedLive} from './SharedLive';
import type {livePresentation} from '../../../packages/domain/src/live-presentation';
import {useEffect,useState} from 'react';
import type {ContestConfiguration, GameFact, Contest as ContestModel, standings, revealView} from '../../../packages/domain/src/index';
import {api,choiceLabel} from './Contest';
export type DayView={live?:ReturnType<typeof livePresentation>;commentary?:{id:string;text:string};contest:ContestModel;reveal?:ReturnType<typeof revealView>;board?:ReturnType<typeof standings>;games?:Record<string,GameFact>;overrideGameIds?:string[];providerUpdatedAt?:string};
export function GameDay({id,config,admin,shared=false,participantId}:{id:string;config:ContestConfiguration;admin:boolean;shared?:boolean;participantId?:string}) {
  const [refreshError,setRefreshError]=useState('');const [view,setView]=useState<DayView>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const [game,setGame]=useState(config.games[0]!.id);const [status,setStatus]=useState('FINAL');
  const [home,setHome]=useState('');const [away,setAway]=useState('');const [firstTeam,setFirstTeam]=useState('');const [firstScore,setFirstScore]=useState('');const [half,setHalf]=useState('');const [reason,setReason]=useState('');
  const base=`/contests/${encodeURIComponent(id)}/game-day`;
  const load=async()=>setView(await api<DayView>(base));
  useEffect(()=>{let active=true;const refresh=()=>api<DayView>(base).then(v=>{if(active){setView(v);setRefreshError('');}}).catch(()=>{if(active)setRefreshError('Could not refresh game-day data.');});void refresh();const timer=setInterval(refresh,3000);return()=>{active=false;clearInterval(timer)};},[base]);
  const act=async(action:string,body:Record<string,unknown>={})=>{if(!view)return;setBusy(true);setError('');try{await api(`${base}/${action}`,'POST',{...body,expectedVersion:view.contest.version});await load();}catch(e){setError(e instanceof Error?e.message:'Request failed');await load().catch(()=>{});}finally{setBusy(false)}};
  const selectGame=(id:string)=>{setGame(id);const f=view?.games?.[id];setStatus(f?.status==='SCHEDULED'?'IN_PROGRESS':f?.status??'FINAL');setHome(f?.home===undefined?'':String(f.home));setAway(f?.away===undefined?'':String(f.away));setFirstTeam(f?.firstTeam??'');setFirstScore(f?.firstScore??'');setHalf(f?.halftime??'');setReason('');};
  if(!view || view.contest.phase==='PREGAME')return null;
  if(shared&&view.board&&view.live)return <SharedLive id={id} config={config} view={view} refreshError={refreshError}/>;
  const selected=config.games.find(g=>g.id===game)!;
  const label=(slotId:string,choiceId:string)=>{const slot=config.slots.find(s=>s.id===slotId);const choice=slot?.choices.find(c=>c.id===choiceId);return choice?choiceLabel(choice,config):'Unanswered'};
  return <section className="game-day">{view.contest.phase==='MAIN_EVENT'&&<MainEvent config={config} view={view} participantId={participantId}/>}<h2>{view.contest.phase==='REVEAL'?'The Reveal':view.contest.phase==='FINAL'?'Final standings':'Standings'}</h2>
    {view.commentary&&<aside className="host-commentary" aria-label="Tailgate commentary"><span>FROM THE CHEAP SEATS</span><p>{view.commentary.text}</p></aside>}
    {(error||refreshError)&&<p role="alert" className="error">{error||refreshError}</p>}
    {view.reveal&&<><h3>{view.reveal.title}</h3><p>Picks are frozen. Full cards unlock after the final Reveal step.</p>{view.reveal.groups.length===0&&<p>{view.reveal.step===0?'Let’s see what everyone picked.':'No matching picks for this step.'}</p>}{view.reveal.groups.map(g=><article key={g.slotId}><h4>{g.label}</h4>{g.choices.map(ch=><p key={ch.choiceId}><strong>{label(g.slotId,ch.choiceId)}</strong>: {ch.players.map(p=>`${p.displayName}${p.confidence?` (${p.confidence} pts)`:''}`).join(', ')}</p>)}</article>)}{admin&&<button disabled={busy} onClick={()=>void act('advance')}>{view.reveal.step===5?'Finish Reveal and publish all picks':'Next Reveal step'}</button>}</>}
    {view.board&&<><details open={view.contest.phase!=='MAIN_EVENT'}><summary>All picks and game results</summary><p>{view.contest.phase==='FINAL'?'Scoring finalized.':'PTS are banked. PROJ adds what live games would score if they ended now, not a forecast. LEFT is the sum of unresolved pick values; conflicting picks may not all win.'}</p>{view.contest.phase==='FINAL'&&<h3>Champion{view.board.champions.length===1?'':'s'}: {view.board.entries.filter(e=>view.board!.champions.includes(e.participantId)).map(e=>e.displayName).join(', ')||'No players'}</h3>}
      <div className="standings">{view.board.entries.map(e=><details key={e.participantId}><summary>#{e.rank} {e.displayName} · {e.points} PTS · {e.projectedPoints??e.points} PROJ · {e.remainingPoints??0} LEFT</summary><p>Projected rank: #{e.projectedRank??e.rank}</p>{view.board?.paths?.filter(p=>p.participantId===e.participantId).map(path=><p key={path.participantId}><strong>{path.status==='ALIVE'?'A winning path remains':path.status==='NO_PATH'?'No winning path under current facts':path.status==='PENDING_EARLIER_GAMES'?'Winning scenarios open after earlier games resolve':'Main Event resolved'}</strong>{path.example&&<>. One example: final score {path.example.home}–{path.example.away} (home–away), first score {path.example.firstTeam} / {path.example.firstScore}, halftime {path.example.halftime}. You finish with {path.example.points} points{path.example.coChampion?' as co-champion':' as champion'}.</>}</p>)}{config.slots.map(s=>{const p=e.picks.find(p=>p.slotId===s.id);const grade=e.grades.find(g=>g.slotId===s.id);return <p key={s.id}><strong>{s.label}</strong>: {p?label(s.id,p.choiceId):'Unanswered'}{p?.confidence?` (${p.confidence} confidence)`:''} — {grade?.result} · {grade?.points??0} pts</p>})}{e.prediction&&<p>Final score prediction: {e.prediction.home}–{e.prediction.away} (home–away)</p>}</details>)}</div>
      <p>Winning paths assume completed games, current facts and final scores up to 200 per team. They are possibilities, not odds; cancellations or corrections can change them.</p><h3>Game results</h3>{view.providerUpdatedAt&&<p>Latest provider change: {new Date(view.providerUpdatedAt).toLocaleString()}</p>}{config.games.map(g=>{const f=view.games?.[g.id];return <p key={g.id}>{g.awayTeamId} at {g.homeTeamId}: {f?`${f.status}${f.home!==undefined?` · ${f.away}–${f.home} (away–home)`:''}`:'Awaiting result'}{f?.period?` · Period ${f.period}`:''}{f?.clock?` · ${f.clock} (observed)`:''}{view.overrideGameIds?.includes(g.id)?' · Commissioner override':''}</p>})}
      </details>{admin&&view.contest.phase!=='FINAL'&&<details><summary>Commissioner results entry</summary><p>Enter observed results. Corrections replace the prior manual entry and are audited. Full final scores resolve winner, ATS and total together. Use VOID for a proposition that cannot be resolved today.</p><form onSubmit={e=>{e.preventDefault();const fact:Record<string,unknown>={status};if(status!=='VOID'){if(home!==''&&away!==''){fact.home=Number(home);fact.away=Number(away)}if(firstTeam)fact.firstTeam=firstTeam;if(firstScore)fact.firstScore=firstScore;if(half)fact.halftime=half;}void act('result',{gameId:game,fact,reason});}}>
        <label>Game<select value={game} onChange={e=>selectGame(e.target.value)}>{config.games.map(g=><option key={g.id} value={g.id}>{g.awayTeamId} at {g.homeTeamId}</option>)}</select></label>
        <fieldset disabled={busy}><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="IN_PROGRESS">In progress</option><option value="FINAL">Final</option><option value="VOID">Void — cannot resolve today</option></select></label>
        {status!=='VOID'&&<><div className="inline"><label>{selected.awayTeamId} score<input type="number" min="0" max="200" required={status==='FINAL'} value={away} onChange={e=>setAway(e.target.value)}/></label><label>{selected.homeTeamId} score<input type="number" min="0" max="200" required={status==='FINAL'} value={home} onChange={e=>setHome(e.target.value)}/></label></div>
        {game===config.mainEventGameId&&<><label>First team to score<select value={firstTeam} onChange={e=>setFirstTeam(e.target.value)}><option value="">Not entered</option>{[selected.homeTeamId,selected.awayTeamId,'VOID'].map(t=><option key={t}>{t}</option>)}</select></label><label>First scoring play<select value={firstScore} onChange={e=>setFirstScore(e.target.value)}><option value="">Not entered</option>{['TOUCHDOWN','FIELD_GOAL','OTHER','VOID'].map(t=><option key={t}>{t}</option>)}</select></label><label>Halftime leader<select value={half} onChange={e=>setHalf(e.target.value)}><option value="">Not entered</option>{[selected.homeTeamId,selected.awayTeamId,'TIE','VOID'].map(t=><option key={t}>{t}</option>)}</select></label></>}
        </>}
        <label>Source / reason for entry or correction<input required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button>Save commissioner override</button></fieldset></form>{view.overrideGameIds?.includes(game)&&<button disabled={busy||!reason.trim()} onClick={()=>void act('clear-override',{gameId:game,reason})}>Remove override and use CFBD</button>}
        <button disabled={busy||config.games.some(g=>!['FINAL','VOID'].includes(view.games?.[g.id]?.status??''))||Object.values(view.board.results).some(r=>r.status==='UNRESOLVED')} onClick={()=>{if(window.confirm('Finalize these results and permanently close commissioner results entry?'))void act('finalize')}}>Finalize standings</button></details>}
    </>}
  </section>;
}
