import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { parseConfiguration } from '../dist/apps/api/src/configuration-input.js';
const origin = process.argv[2];
assert.match(origin, /^https:\/\/[a-z0-9]+\.cloudfront\.net$/);
const payload = JSON.parse(await readFile(process.argv[3], 'utf8'));
parseConfiguration(payload.configuration);
assert.match(payload.contest.id, /^[a-zA-Z0-9][a-zA-Z0-9_-]{0,79}$/);
assert.equal(payload.configuration.contestId, payload.contest.id);
assert.ok(Date.parse(payload.contest.lockAt) > Date.now(), 'Cannot seed an already-locked contest');
const path = `/api/contests/${payload.contest.id}`;
const existing = await fetch(origin + path, { redirect: 'error', signal: AbortSignal.timeout(20000) });
if (existing.status !== 404) throw new Error(`Refusing to overwrite or retry an ambiguous existing contest (HTTP ${existing.status})`);
const secrets = await readFile(new URL('../infra/terraform/secrets.auto.tfvars', import.meta.url), 'utf8');
const password = JSON.parse(secrets.match(/^commissioner_password\s*=\s*(".*")$/m)[1]);
const request = (path, body, cookie = '') => fetch(origin + path, { method: 'POST', headers: { origin, 'content-type': 'application/json', cookie }, body: JSON.stringify(body), redirect: 'error', signal: AbortSignal.timeout(20000) });
const login = await request('/api/commissioner/login', { password });
assert.equal(login.status, 200, 'Commissioner login failed');
const cookie = login.headers.getSetCookie()[0]?.split(';')[0];
assert.ok(cookie, 'No commissioner cookie returned');
const created = await request('/api/contests', payload, cookie);
assert.equal(created.status, 201, 'Contest creation failed; inspect existing contest before retry');
const read = await fetch(origin + path, { redirect: 'error', signal: AbortSignal.timeout(20000) });
assert.equal(read.status, 200);
const view = await read.json();
assert.equal(view.contest.lockAt, payload.contest.lockAt);
assert.equal(view.configuration.slots.length, 15);
assert.equal(view.configuration.games.length, payload.configuration.games.length);
assert.deepEqual(view.participants, []);
assert.equal(view.cards, undefined);
console.log(`Created and verified ${origin}/?contest=${payload.contest.id}`);
console.log(`Lock: ${view.contest.lockAt}; ${view.configuration.games.length} games; 15 pick slots; no participants or picks seeded`);
