import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { DynamoDBClient, CreateTableCommand, DeleteTableCommand, waitUntilTableExists } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, GetCommand } from '@aws-sdk/lib-dynamodb';
import { DynamoContestRepository, keys } from './dynamo.js';
import { createService, type ApiResponse } from '../../../apps/api/src/service.js';
import { fixture } from '../../domain/src/fixture.js';
// Explicit loopback endpoint and dummy credentials prevent accidental use of an AWS account.
const endpoint = process.env.TAILGATE_DYNAMO_TEST_ENDPOINT;
test('DynamoDB Local: API joins, atomic session exchange, cards, privacy, denial, and lock', { skip: !endpoint }, async () => {
  const url = new URL(endpoint!);
  assert.ok(url.protocol === 'http:' && ['127.0.0.1','localhost','[::1]'].includes(url.hostname) && !url.username && !url.password, 'Use a loopback DynamoDB Local endpoint');
  const client = new DynamoDBClient({ endpoint, region: 'us-east-1', credentials: { accessKeyId: 'localtest', secretAccessKey: 'localtest' } });
  const document = DynamoDBDocumentClient.from(client, { marshallOptions: { removeUndefinedValues: true } });
  const table = `tailgate-test-${randomUUID()}`;
  await client.send(new CreateTableCommand({ TableName: table, BillingMode: 'PAY_PER_REQUEST', KeySchema: [{ AttributeName:'PK',KeyType:'HASH' },{AttributeName:'SK',KeyType:'RANGE'}], AttributeDefinitions:[{AttributeName:'PK',AttributeType:'S'},{AttributeName:'SK',AttributeType:'S'}] }));
  try {
    await waitUntilTableExists({ client, maxWaitTime: 20, minDelay: 1, maxDelay: 2 }, { TableName: table });
    let at = new Date('2026-09-12T15:00:00Z');
    const repository = new DynamoContestRepository(document, table, () => at);
    const settings = { origin:'https://tailgate.test',password:'local-test-password',signingSecret:'local-test-signing-secret-at-least-32-characters',secureCookies:true,now:()=>at };
    const service = createService(repository, settings);
    const body = (r: ApiResponse) => r.body as any;
    const cookie = (r: ApiResponse) => r.cookies?.[0]?.split(';')[0] ?? '';
    const call = (method: string, path: string, data?: unknown, session='') => service({method,path,body:data,headers:{origin:settings.origin,cookie:session}});
    const admin = cookie(await call('POST','/api/commissioner/login',{password:settings.password}));
    const { c, card } = fixture();
    const payload = {contest:{id:'week',name:'Week',timezone:'UTC',lockAt:'2026-09-12T16:00:00Z'},configuration:c};
    assert.equal((await call('POST','/api/contests',payload,admin)).statusCode,201);
    assert.equal((await call('POST','/api/contests',payload,admin)).statusCode,409);
    const request = body(await call('POST','/api/contests/week/join-requests',{displayName:'Player'}));
    const path = `/api/contests/week/join-requests/${request.requestId}`;
    const approved = await call('POST',`${path}/approve`,{attendance:'REMOTE'},admin);
    assert.equal(approved.statusCode,200); assert.equal(approved.cookies,undefined);
    assert.equal((await call('POST',`${path}/deny`,{},admin)).statusCode,409);
    assert.equal((await call('POST',path,{requestSecret:'wrong'})).statusCode,401);
    const exchanges = await Promise.all([1,2].map(()=>call('POST',path,{requestSecret:request.requestSecret})));
    const winner = exchanges.find(r=>r.cookies?.length)!;
    assert.ok(winner); assert.equal(exchanges.filter(r=>r.cookies?.length).length,1);
    const session = cookie(winner);
    assert.equal((await call('POST',path,{requestSecret:request.requestSecret},session)).statusCode,200);
    const stored = await document.send(new GetCommand({TableName:table,Key:keys.session(session.split('=')[1]!),ConsistentRead:true}));
    assert.equal(stored.Item!.data.participantId,body(approved).participantId);
    assert.equal(JSON.stringify(stored.Item).includes(session.split('=')[1]!),false);
    assert.equal((await call('PUT','/api/contests/week/me/pick-card',{...card,expectedCardRevision:0},session)).statusCode,200);
    const stale = await call('PUT','/api/contests/week/me/pick-card',{...card,expectedCardRevision:0},session);
    assert.equal(stale.statusCode,409); assert.equal(body(stale).error.details.cardRevision,1);
    assert.equal((await call('POST','/api/contests/week/me/submit',{expectedCardRevision:1},session)).statusCode,200);
    const view = body(await call('GET','/api/contests/week/pregame',undefined,admin));
    assert.equal(view.cards,undefined); assert.equal(view.participants[0].picks,undefined); assert.equal(view.participants[0].completedSelections,15);
    const denied = body(await call('POST','/api/contests/week/join-requests',{displayName:'Denied'}));
    assert.equal((await call('POST',`/api/contests/week/join-requests/${denied.requestId}/deny`,{},admin)).statusCode,200);
    assert.equal(body(await call('POST',`/api/contests/week/join-requests/${denied.requestId}`,{requestSecret:denied.requestSecret})).status,'DENIED');
    at = new Date('2026-09-12T16:00:00Z');
    assert.equal((await call('PUT','/api/contests/week/me/pick-card',{...card,expectedCardRevision:2},session)).statusCode,409);
    assert.equal((await call('POST','/api/contests/week/join-requests',{displayName:'Late'})).statusCode,409);
    await repository.revokeSession(session.split('=')[1]!);
    assert.equal((await call('GET','/api/contests/week/me/pick-card',undefined,session)).statusCode,401);
  } finally { await client.send(new DeleteTableCommand({TableName:table})); client.destroy(); }
});
